name: brainstream
favicon: null
layout_spectrum: 0.7257027958985418
typography_spectrum: 0.6504054660908878
title: stream your life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7902278460096568
  lightness: 0.911015447229147
  saturation: 0.11962259863503277
  rhythmicContrast: 0.9541943660005927
purpose: []
